import Head from 'next/head'
import CurriculoSection from '../components/sections/CurriculoSection'
import ProjectsSection from '../components/sections/ProjectsSection'
import { Inter } from '@next/font/google'
import Drawer from '../components/Drawer'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${inter.variable}`}>
        <Drawer>
          <ProjectsSection />
        </Drawer>
      </main>
    </>
  )
}
