name: CI

on: 
  push: 
    branches:
      - main
  pull_request: 
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run:  npm install && npm run build  # Create nextjs build on .next folder
        
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.next'
          destination-github-username: 'Unidade'
          destination-repository-name: 'Unidade.github.io'
          user-email: dario.rodri123@gmail.com
          target-directory: ./next
          target-branch: main
